{
 "title": "Internals",
 "tags": [ "on_main" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "hypertable_detailed_size [2.x]",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select 'metric-data' as name, table_bytes, index_bytes, toast_bytes, total_bytes from hypertable_detailed_size('metric-data')\nunion all\nselect 'analytic-event-data' as name, table_bytes, index_bytes, toast_bytes, total_bytes from hypertable_detailed_size('analytic-event-data')\nunion all\nselect 'transaction-sample-data' as name, table_bytes, index_bytes, toast_bytes, total_bytes from hypertable_detailed_size('transaction-sample-data')\nunion all\nselect 'errors-data' as name, table_bytes, index_bytes, toast_bytes, total_bytes from hypertable_detailed_size('error-data')"
    }
   ]
  },
  {
   "title": "hypertable_compression_stats [2.x]",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select 'metric-data' as name, total_chunks, number_compressed_chunks, before_compression_total_bytes, after_compression_total_bytes from hypertable_compression_stats('metric-data')\nunion all\nselect 'analytic-event-data' as name, total_chunks, number_compressed_chunks, before_compression_total_bytes, after_compression_total_bytes from hypertable_compression_stats('analytic-event-data')\nunion all\nselect 'transaction-sample-data' as name, total_chunks, number_compressed_chunks, before_compression_total_bytes, after_compression_total_bytes from hypertable_compression_stats('transaction-sample-data')\nunion all\nselect 'errors-data' as name, total_chunks, number_compressed_chunks, before_compression_total_bytes, after_compression_total_bytes from hypertable_compression_stats('error-data')\n\n\n\n"
    }
   ]
  },
  {
   "title": "hypertable_relation_size [1.x]",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "select 'metric-data' as name, * from hypertable_relation_size('metric-data')\nunion all\nselect 'analytic-event-data' as name, * from hypertable_relation_size('analytic-event-data')\nunion all\nselect 'transaction-sample-data' as name, * from hypertable_relation_size('transaction-sample-data')\nunion all\nselect 'errors-data' as name, * from hypertable_relation_size('error-data')\n\n\n"
    }
   ]
  },
  {
   "title": "timescaledb_information.compressed_hypertable_stats [1.x]",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "select hypertable_name, total_chunks, number_compressed_chunks, uncompressed_total_bytes, compressed_total_bytes from timescaledb_information.compressed_hypertable_stats;"
    }
   ]
  }
 ]
}