{
 "title": "Background",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "app_id", "query": "not_selected" }
  ]
 },
 "panels": [
  {
   "title": "App name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select name\nfrom apps\nwhere id = $app_id\n"
    }
   ]
  },
  {
   "title": "Response",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  name as metric,\n\n  sum(val)\n  /\n  sum(sum(\"call-count\")) filter (where name = 'OtherTransaction/all')\n                         over (partition by time)\n  as val\nfrom (\n  select\n    $__timeGroup(point, $interval, 0),\n    name,\n    \"call-count\",\n    case when \"total-exclusive-time\" = 0\n    then \"total-call-time\"\n    else \"total-exclusive-time\"\n    end as val\n  from \"metric-data-ext\"\n  where\n    $__timeFilter(point)\n    and \"app-id\" = $app_id\n    and scope = ''\n    and name like any(array[\n      'OtherTransaction/all',\n      'External/allOther',\n      'Datastore/%/allOther',\n      'GC/cumulative'\n    ])\n) as x\ngroup by time, name\norder by time"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  sum(\"call-count\") / extract(epoch from interval '$interval') * 60 as val,\n  'current' as metric\nfrom \"metric-data-ext\"\nwhere\n  point between\n    $__timeFrom()::timestamptz\n    and\n    $__timeTo()::timestamptz\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'OtherTransaction/all'\ngroup by time\nunion all\nselect\n  $__timeGroup(point + interval '1 day', $interval, 0),\n  sum(\"call-count\") / extract(epoch from interval '$interval') * 60 as val,\n  '-1 day' as metric\nfrom \"metric-data-ext\"\nwhere\n  point between\n    $__timeFrom()::timestamptz - interval '1 day'\n    and\n    $__timeTo()::timestamptz - interval '1 day'\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'OtherTransaction/all'\ngroup by time\nunion all\nselect\n  $__timeGroup(point + interval '1 week', $interval, 0),\n  sum(\"call-count\") / extract(epoch from interval '$interval') * 60 as val,\n  '-1 week' as metric\nfrom \"metric-data-ext\"\nwhere\n  point between\n    $__timeFrom()::timestamptz - interval '1 week'\n    and\n    $__timeTo()::timestamptz - interval '1 week'\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'OtherTransaction/all'\ngroup by time\norder by time"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "select *\nfrom (\n  select\n    time,\n    name as metric,\n    sum(\"call-count\")\n    / sum(sum(\"call-count\")) filter (where name = 'OtherTransaction/all')\n                             over (partition by time)\n    -- здесь не нужно делать поправку на $interval, т.к. это безразмерные проценты\n    as val\n  from (\n    select\n      $__timeGroup(point, $interval, 0),\n      name,\n      \"call-count\"\n    from \"metric-data-ext\"\n    where\n      $__timeFilter(point)\n      and \"app-id\" = $app_id\n      and scope = ''\n      and name in ('OtherTransaction/all', 'Errors/allOther')\n  ) as x\n  group by time, name\n) as res\nwhere metric != 'OtherTransaction/all'\norder by time\n"
    }
   ]
  },
  {
   "title": "Histogram",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "with\nstat as (\n  select\n    percentile_cont(0.99) within group (order by duration asc) as max,\n    count(*) as total\n  from \"analytic-event-data-ext\"\n  where\n    $__timeFilter(timestamp)\n    and \"app-id\" = $app_id\n    and \"transaction-name\" like any(array['OtherTransaction/%'])\n),\nbucket_nums as (\n  select * from generate_series(1, 101) as buckets(i)\n),\nbuckets as (\n  select\n    width_bucket(duration, 0, max, 100) as bucket,\n    count(*) as count\n  from \"analytic-event-data-ext\", stat\n  where\n    $__timeFilter(timestamp)\n    and \"app-id\" = $app_id\n    and \"transaction-name\" like any(array['OtherTransaction/%'])\n  group by bucket\n)\n  select\n    (i - 1) * max / 100 as start,\n    coalesce(count::float, .0) / total::float * 100 as percent,\n    coalesce(count, 0) as count\n  from stat, bucket_nums\n  left join buckets on i = bucket\n"
    }
   ]
  },
  {
   "title": "Percentiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(timestamp, $interval, 0),\n  percentile_cont(0.99) within group (order by duration asc) as \"0.99\",\n  percentile_cont(0.95) within group (order by duration asc) as \"0.95\",\n  percentile_cont(0.50) within group (order by duration asc) as median,\n  avg(duration) as avg\nfrom \"analytic-event-data-ext\"\nwhere\n  $__timeFilter(timestamp)\n  and \"app-id\" = $app_id\n  and \"transaction-name\" like any(array['OtherTransaction/%'])\ngroup by time\n"
    }
   ]
  },
  {
   "title": "Historical response",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  sum(\"total-call-time\") / sum(\"call-count\") as val,\n  'current' as metric\nfrom \"metric-data-ext\"\nwhere\n  point between\n    $__timeFrom()::timestamptz\n    and\n    $__timeTo()::timestamptz\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'OtherTransaction/all'\ngroup by time\nunion all\nselect\n  $__timeGroup(point + interval '1 day', $interval, 0),\n  sum(\"total-call-time\") / sum(\"call-count\") as val,\n  '-1 day' as metric\nfrom \"metric-data-ext\"\nwhere\n  point between\n    $__timeFrom()::timestamptz - interval '1 day'\n    and\n    $__timeTo()::timestamptz - interval '1 day'\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'OtherTransaction/all'\ngroup by time\nunion all\nselect\n  $__timeGroup(point + interval '1 week', $interval, 0),\n  sum(\"total-call-time\") / sum(\"call-count\") as val,\n  '-1 week' as metric\nfrom \"metric-data-ext\"\nwhere\n  point between\n    $__timeFrom()::timestamptz - interval '1 week'\n    and\n    $__timeTo()::timestamptz - interval '1 week'\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'OtherTransaction/all'\ngroup by time\norder by time"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "select\n  replace(name, 'OtherTransaction/', '')  as metric,\n  sum(\"total-call-time\") / sum(sum(\"total-call-time\")) over () as percent,\n  sum(\"total-call-time\") / sum(\"call-count\") as avg,\n  sum(\"call-count\")\n    * 60\n    / extract(epoch from $__timeTo()::timestamp - $__timeFrom()::timestamp)\n    as rpm,\n  min(\"min-call-time\") as min,\n  max(\"max-call-time\") as max\nfrom \"metric-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name like 'OtherTransaction/%'\n  and name not like 'OtherTransaction%/all'\ngroup by name"
    }
   ]
  },
  {
   "title": "By server",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "with\ndata as (\n  select\n    \"server-id\",\n    name,\n    sum(\"call-count\") as \"call-count\",\n    sum(\"total-call-time\") as \"total-call-time\",\n    sum(\"total-exclusive-time\") as \"total-exclusive-time\"\n  from \"metric-data-ext\"\n  where\n    $__timeFilter(point)\n    and \"app-id\" = $app_id\n    and scope = ''\n    and name = any(array[\n      'OtherTransaction/all',\n      'Errors/allOther',\n      'CPU/User Time',\n      'Memory/Physical'\n    ])\n  group by \"server-id\", name\n),\nother_tx as (\n  select\n    \"server-id\",\n    \"total-call-time\" as time,\n    \"call-count\" as calls\n  from data\n  where name = 'OtherTransaction/all'\n),\nerrors as (\n  select\n    \"server-id\",\n    \"call-count\" as count\n  from data\n  where name = 'Errors/allOther'\n),\ncpu as (\n  select\n    \"server-id\",\n    \"total-call-time\" / 60 / extract(epoch from $__timeTo()::timestamp - $__timeFrom()::timestamp) * 60 as val\n  from data\n  where name = 'CPU/User Time'\n),\nmemory as (\n  select\n    \"server-id\",\n    \"total-call-time\" / extract(epoch from $__timeTo()::timestamp - $__timeFrom()::timestamp) * 60 as val\n  from data\n  where name = 'Memory/Physical'\n)\nselect\n  servers.host,\n  other_tx.time / other_tx.calls as resp,\n  other_tx.calls / extract(epoch from $__timeTo()::timestamp - $__timeFrom()::timestamp) * 60 as rpm,\n  errors.count / other_tx.calls as errors,\n  cpu.val as cpu,\n  memory.val as memory\nfrom servers\njoin other_tx on servers.id = other_tx.\"server-id\"\nleft join errors on servers.id = errors.\"server-id\"\nleft join cpu on servers.id = cpu.\"server-id\"\nleft join memory on servers.id = memory.\"server-id\"\nwhere\n  servers.\"app-id\" = $app_id"
    }
   ]
  }
 ]
}