{
 "title": "BackgroundTransaction",
 "time": { "from": "2020-01-30T12:18:40.434Z", "to": "2020-01-30T12:48:40.436Z" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "app_id", "query": "not_selected" },
   { "name": "scope", "query": "not_selected" }
  ]
 },
 "panels": [
  {
   "title": "App name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select name\nfrom apps\nwhere id = $app_id\n"
    }
   ]
  },
  {
   "title": "Scope",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "rawSql": "select '$scope'" }
   ]
  },
  {
   "title": "Breakdown",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time, metric,\n  sum(val) as val\nfrom (\n  select\n    time,\n\n    case\n      when dense_rank() over (order by total desc) > 5\n      then 'Other'\n      else name\n    end as metric,\n\n    \"total-exclusive-time\"\n      /\n      sum(\"call-count\")\n      filter (where name = 'OtherTransaction/$scope')\n      over (partition by time)\n    as val\n  from (\n    select\n      $__timeGroup(point, $interval, 0),\n      name,\n      sum(\"total-exclusive-time\") as \"total-exclusive-time\",\n      sum(sum(\"total-exclusive-time\")) over (partition by name) as total,\n      sum(\"call-count\") as \"call-count\"\n    from \"metric-data-ext\"\n    where\n      $__timeFilter(point)\n      and \"app-id\" = $app_id\n      and\n      (\n        scope = 'OtherTransaction/$scope'\n        or\n        (scope = '' and name = 'OtherTransaction/$scope')\n      )\n    group by time, name\n  ) as x\n) as res\nwhere metric != 'OtherTransaction/$scope'\ngroup by time, metric\norder by time"
    }
   ]
  },
  {
   "title": "Histogram",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "with\nstat as (\n  select\n    percentile_cont(0.99) within group (order by duration asc) as max,\n    count(*) as total\n  from \"analytic-event-data-ext\"\n  where\n    $__timeFilter(timestamp)\n    and \"app-id\" = $app_id\n    and \"transaction-name\" = any(array['OtherTransaction/$scope'])\n),\nbucket_nums as (\n  select * from generate_series(1, 101) as buckets(i)\n),\nbuckets as (\n  select\n    width_bucket(duration, 0, max, 100) as bucket,\n    count(*) as count\n  from \"analytic-event-data-ext\", stat\n  where\n    $__timeFilter(timestamp)\n    and \"app-id\" = $app_id\n    and \"transaction-name\" = any(array['OtherTransaction/$scope'])\n  group by bucket\n)\n  select\n    (i - 1) * max / 100 as start,\n    coalesce(count::float, .0) / total::float * 100 as percent,\n    coalesce(count, 0) as count\n  from stat, bucket_nums\n  left join buckets on i = bucket\n"
    }
   ]
  },
  {
   "title": "Percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(timestamp, $interval, 0),\n  percentile_cont(0.99) within group (order by duration asc) as \"0.99\",\n  percentile_cont(0.95) within group (order by duration asc) as \"0.95\",\n  percentile_cont(0.50) within group (order by duration asc) as median,\n  avg(duration) as avg\nfrom \"analytic-event-data-ext\"\nwhere\n  $__timeFilter(timestamp)\n  and \"app-id\" = $app_id\n  and \"transaction-name\" = any(array['OtherTransaction/$scope'])\ngroup by time"
    }
   ]
  },
  {
   "title": "Historical response",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  sum(\"total-call-time\") / sum(\"call-count\") as val,\n  'current' as metric\nfrom \"metric-data-ext\"\nwhere\n  point between\n    $__timeFrom()::timestamptz\n    and\n    $__timeTo()::timestamptz\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'OtherTransaction/$scope'\ngroup by time\nunion all\nselect\n  $__timeGroup(point + interval '1 day', $interval, 0),\n  sum(\"total-call-time\") / sum(\"call-count\") as val,\n  '-1 day' as metric\nfrom \"metric-data-ext\"\nwhere\n  point between\n    $__timeFrom()::timestamptz - interval '1 day'\n    and\n    $__timeTo()::timestamptz - interval '1 day'\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'OtherTransaction/$scope'\ngroup by time\nunion all\nselect\n  $__timeGroup(point + interval '1 week', $interval, 0),\n  sum(\"total-call-time\") / sum(\"call-count\") as val,\n  '-1 week' as metric\nfrom \"metric-data-ext\"\nwhere\n  point between\n    $__timeFrom()::timestamptz - interval '1 week'\n    and\n    $__timeTo()::timestamptz - interval '1 week'\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'OtherTransaction/$scope'\ngroup by time\norder by time"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  sum(\"call-count\") / extract(epoch from interval '$interval') * 60 as val,\n  'current' as metric\nfrom \"metric-data-ext\"\nwhere\n  point between\n    $__timeFrom()::timestamptz\n    and\n    $__timeTo()::timestamptz\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'OtherTransaction/$scope'\ngroup by time\nunion all\nselect\n  $__timeGroup(point +  interval '1 day', $interval, 0),\n  sum(\"call-count\") / extract(epoch from interval '$interval') * 60 as val,\n  '-1 day' as metric\nfrom \"metric-data-ext\"\nwhere\n  point between\n    $__timeFrom()::timestamptz - interval '1 day'\n    and\n    $__timeTo()::timestamptz - interval '1 day'\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'OtherTransaction/$scope'\ngroup by time\nunion all\nselect\n  $__timeGroup(point + interval '1 week', $interval, 0),\n  sum(\"call-count\") / extract(epoch from interval '$interval') * 60 as val,\n  '-1 week' as metric\nfrom \"metric-data-ext\"\nwhere\n  point between\n    $__timeFrom()::timestamptz - interval '1 week'\n    and\n    $__timeTo()::timestamptz - interval '1 week'\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'OtherTransaction/$scope'\ngroup by time\norder by time"
    }
   ]
  },
  {
   "title": "Table",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "select\n  name,\n  \"total-exclusive-time\"\n    / sum(\"total-exclusive-time\") over ()\n  as percent,\n  \"call-count\" / total as avg_calls,\n  \"total-exclusive-time\" / total as avg_time\nfrom (\n  select\n    name,\n    sum(\"total-exclusive-time\") as \"total-exclusive-time\",\n    sum(\"call-count\") as \"call-count\",\n    sum(sum(\"call-count\"))\n    filter (where name = 'OtherTransaction/$scope')\n    over () as total\n  from \"metric-data-ext\"\n  where\n    $__timeFilter(point)\n    and \"app-id\" = $app_id\n    and\n    (\n      scope = 'OtherTransaction/$scope'\n      or\n      (scope = '' and name = 'OtherTransaction/$scope')\n    )\n  group by name\n) as x\nwhere name != 'OtherTransaction/$scope'"
    }
   ]
  },
  {
   "title": "Transaction traces",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "select data.id, \"start-time\", duration, host\nfrom \"transaction-sample-data-ext\" as data\njoin servers on servers.id = data.\"server-id\"\nwhere\n  $__timeFilter(\"start-time\")\n  and data.\"app-id\" = $app_id\n  and data.\"transaction-name\" = 'OtherTransaction/$scope'\norder by duration desc"
    }
   ]
  }
 ]
}