{
 "title": "Databases",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "app_id", "query": "not_selected" }
  ]
 },
 "panels": [
  {
   "title": "App name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select name\nfrom apps\nwhere id = $app_id\n"
    }
   ]
  },
  {
   "title": "Top databases operations by time consumed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  name as metric,\n  val\nfrom (\n  select\n    time,\n    name,\n    val,\n    dense_rank() over (order by total desc) as rank\n  from (\n    select\n      $__timeGroup(point, $interval, 0),\n      name,\n      sum(\"total-call-time\") as val,\n      sum(sum(\"total-call-time\")) over (partition by name) as total\n    from \"metric-data-ext\"\n    where\n      $__timeFilter(point)\n      and \"app-id\" = $app_id\n      and scope = ''\n      and name like 'Datastore/operation/%'\n    group by time, name\n  ) as x\n) as res\nwhere rank <= 5\norder by time"
    }
   ]
  },
  {
   "title": "Table",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select\n  name,\n  sum(\"call-count\") as \"call-count\",\n  sum(\"call-count\")\n    / extract(epoch from $__timeTo()::timestamp - $__timeFrom()::timestamp)\n    * 60 as opm,\n  sum(\"total-call-time\") / sum(\"call-count\") as avg,\n  min(\"min-call-time\") as min,\n  max(\"max-call-time\") as max\nfrom \"metric-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name like any(array['Datastore/operation/%', 'Datastore/statement/%'])\ngroup by name"
    }
   ]
  },
  {
   "title": "Query time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  name as metric,\n  sum(\"total-call-time\") / sum(\"call-count\") as val\nfrom \"metric-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name like 'Datastore/%/all'\ngroup by name, time \norder by time"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  name as metric,\n  sum(\"call-count\") / extract(epoch from interval '$interval') * 60 as rpm\nfrom \"metric-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name like 'Datastore/%/all'\ngroup by name, time\norder by time\n"
    }
   ]
  }
 ]
}