{
 "title": "Errors",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "app_id", "query": "not_selected" }
  ]
 },
 "panels": [
  {
   "title": "App name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select name\nfrom apps\nwhere id = $app_id\n"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "select *\nfrom (\n  select\n    time,\n    name as metric,\n    sum(\"call-count\")\n    / sum(sum(\"call-count\")) filter (where name = 'HttpDispatcher')\n                             over (partition by time)\n    -- здесь не нужно делать поправку на $interval, т.к. это безразмерные проценты\n    as val\n  from (\n    select\n      $__timeGroup(point, $interval, 0),\n      name,\n      \"call-count\"\n    from \"metric-data-ext\"\n    where\n      $__timeFilter(point)\n      and \"app-id\" = $app_id\n      and scope = ''\n      and name in ('HttpDispatcher', 'Errors/allWeb')\n  ) as x\n  group by time, name\n) as res\nwhere metric != 'HttpDispatcher'\n"
    },
    {
     "rawSql": "select *\nfrom (\n  select\n    time,\n    name as metric,\n    sum(\"call-count\")\n    / sum(sum(\"call-count\")) filter (where name = 'OtherTransaction/all')\n                             over (partition by time)\n    -- здесь не нужно делать поправку на $interval, т.к. это безразмерные проценты\n    as val\n  from (\n    select\n      $__timeGroup(point, $interval, 0),\n      name,\n      \"call-count\"\n    from \"metric-data-ext\"\n    where\n      $__timeFilter(point)\n      and \"app-id\" = $app_id\n      and scope = ''\n      and name in ('OtherTransaction/all', 'Errors/allOther')\n  ) as x\n  group by time, name\n) as res\nwhere metric != 'OtherTransaction/all'\n"
    }
   ]
  },
  {
   "title": "Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "select\n  count(*),\n  min(point) as \"first-occurrence\",\n  max(point) as \"last-occurrence\",\n  \"transaction-name\",\n  \"exception-class-name\",\n  string_agg(distinct message, '<br>' order by message) as message\n\nfrom \"error-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\ngroup by\n  \"transaction-name\",\n  \"exception-class-name\""
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  count(*) as val,\n  \"exception-class-name\" as metric\nfrom \"error-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\ngroup by\n  time, \"exception-class-name\"\norder by time\n"
    }
   ]
  }
 ]
}