{
 "title": "Error",
 "time": { "from": "2020-01-30T12:18:40.434Z", "to": "2020-01-30T12:48:40.436Z" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "app_id", "query": "not_selected" },
   { "name": "scope", "query": "not_selected" },
   { "name": "exception_class_name" }
  ]
 },
 "panels": [
  {
   "title": "App name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select name\nfrom apps\nwhere id = $app_id\n"
    }
   ]
  },
  {
   "title": "Scope",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "rawSql": "select '$scope'" }
   ]
  },
  {
   "title": "Class name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "rawSql": "select '$exception_class_name'" }
   ]
  },
  {
   "title": "Count by time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \n  $__timeGroup(point, $interval, 0),\n  count(*) as value\nfrom \"error-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and \"transaction-name\" = '$scope'\n  and \"exception-class-name\" = '$exception_class_name'\ngroup by point"
    }
   ]
  },
  {
   "title": "Message",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "select message\nfrom \"error-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and \"transaction-name\" = '$scope'\n  and \"exception-class-name\" = '$exception_class_name'\norder by point asc\nlimit 1"
    }
   ]
  },
  {
   "title": "Data",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "select jsonb_pretty(data) as data\nfrom \"error-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and \"transaction-name\" = '$scope'\n  and \"exception-class-name\" = '$exception_class_name'\norder by point asc\nlimit 1"
    }
   ]
  }
 ]
}