{
 "title": "External",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "app_id", "query": "not_selected" }
  ]
 },
 "panels": [
  {
   "title": "App name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select name\nfrom apps\nwhere id = $app_id\n"
    }
   ]
  },
  {
   "title": "Time consumption",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  name as metric,\n  sum(\"total-call-time\") as \"total-call-time\"\nfrom \"metric-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name like 'External/%/all'\ngroup by name, time\norder by time\n"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  name as metric,\n  sum(\"call-count\") / extract(epoch from interval '$interval') * 60 as rpm\nfrom \"metric-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = any(array['External/allOther', 'External/allWeb'])\ngroup by name, time\norder by time"
    }
   ]
  },
  {
   "title": "Table",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "select\n  name,\n  sum(\"call-count\") as \"call-count\",\n  sum(\"call-count\")\n    / extract(epoch from $__timeTo()::timestamp - $__timeFrom()::timestamp)\n    * 60 as opm,\n  sum(\"total-call-time\") / sum(\"call-count\") as avg,\n  min(\"min-call-time\") as min,\n  max(\"max-call-time\") as max\nfrom \"metric-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name like 'External/%'\n  and name not like 'External/%all%'\ngroup by name\n"
    }
   ]
  }
 ]
}