{
 "title": "Extra",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "app_id", "query": "not_selected" },
   { "name": "name", "query": "not_selected" }
  ]
 },
 "panels": [
  {
   "title": "App name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select name\nfrom apps\nwhere id = $app_id\n"
    }
   ]
  },
  {
   "title": "Name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "rawSql": "select '$name'" }
   ]
  },
  {
   "title": "Query time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  sum(\"total-exclusive-time\") / sum(\"call-count\") as value\nfrom \"metric-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = '$name'\ngroup by time\norder by time"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  sum(\"call-count\") / extract(epoch from interval '$interval') * 60 as rpm\nfrom \"metric-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = '$name'\ngroup by time\norder by time\n"
    }
   ]
  },
  {
   "title": "Time consumption by caller",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select\n  now() as time,\n  sum(total) as total,\n  metric\nfrom (\n  select\n    *,\n    case\n      when dense_rank() over (order by total desc) > 5\n      then 'Other'\n      else scope\n    end as metric\n  from (\n    select\n      scope,\n      sum(\"total-exclusive-time\") as total\n    from \"metric-data-ext\"\n    where\n      $__timeFilter(point)\n      and \"app-id\" = $app_id\n      and scope != ''\n      and name = '$name'\n    group by scope\n  ) as res\n) as x\ngroup by metric"
    }
   ]
  }
 ]
}