{
 "title": "Go runtime",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "app_id", "query": "not_selected" }
  ]
 },
 "panels": [
  {
   "title": "App name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select name\nfrom apps\nwhere id = $app_id\n"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "description": "as a percentage of wall clock time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  sum(\"total-call-time\") / sum(\"call-count\") as val\nfrom \"metric-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'Go/Runtime/Goroutines'\ngroup by time\norder by time"
    }
   ]
  },
  {
   "title": "GC pause time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  sum(\"total-call-time\") / sum(\"call-count\") as avg_mem,\n  max(\"max-call-time\") as max_mem\nfrom \"metric-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'GC/System/Pauses'\ngroup by time\norder by time "
    }
   ]
  },
  {
   "title": "GC pause frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  name as metric,\n  sum(\"call-count\") / extract(epoch from interval '$interval') * 60 as val\nfrom \"metric-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'GC/System/Pauses'\ngroup by time, name\norder by time, name"
    }
   ]
  },
  {
   "title": "GC pauses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  sum(\"total-call-time\") / extract(epoch from interval '$interval') * 60 as val\nfrom \"metric-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'GC/System/Pause Fraction'\ngroup by time\norder by time"
    }
   ]
  }
 ]
}