{
 "title": "Ruby WMs",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "app_id", "query": "not_selected" }
  ]
 },
 "panels": [
  {
   "title": "App name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select name\nfrom apps\nwhere id = $app_id\n"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "description": "as a percentage of wall clock time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  -- gc_time / wall_clock_time\n  sum(\"total-exclusive-time\") / sum(\"sum-of-squares\") as val\nfrom \"metric-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'RubyVM/GC/runs'\ngroup by time\norder by time"
    }
   ]
  },
  {
   "title": "Ruby heap size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  name as metric,\n  sum(\"call-count\") / sum(\"sum-of-squares\") as val\nfrom \"metric-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name in ('RubyVM/GC/heap_free', 'RubyVM/GC/heap_live')\ngroup by time, name\norder by time"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  sum(\"total-call-time\") / sum(\"call-count\") as avg_mem,\n  min(\"min-call-time\") as min_mem,\n  max(\"max-call-time\") as max_mem\nfrom \"metric-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'Memory/Physical'\ngroup by time\norder by time"
    }
   ]
  },
  {
   "title": "Object allocations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  sum(\"total-call-time\") / sum(\"call-count\") as val\nfrom \"metric-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'RubyVM/GC/total_allocated_object'\ngroup by time\norder by time\n"
    }
   ]
  },
  {
   "title": "GC frequency",
   "type": "graph",
   "description": "runs per 100 transactions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  name as metric,\n  -- gc_time / wall_clock_time\n  sum(\"total-call-time\") / sum(\"call-count\") * 100 as val\nfrom \"metric-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = any(array[\n    'RubyVM/GC/major_gc_count',\n    'RubyVM/GC/minor_gc_count'\n  ])\ngroup by time, name\norder by time"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  sum(\"call-count\") / sum(\"sum-of-squares\") as val\nfrom \"metric-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'RubyVM/Threads/all'\ngroup by time\norder by time\n"
    }
   ]
  }
 ]
}