{
 "title": "SLA",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "app_id", "query": "not_selected" }
  ]
 },
 "panels": [
  {
   "title": "App name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select name\nfrom apps\nwhere id = $app_id\n"
    }
   ]
  },
  {
   "title": "Daily",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "with data as (\n  select *\n  from \"metric-data-by-day-ext\"\n  where\n    point >= date_trunc('day', now()) - interval '1 week'\n    and \"app-id\" = $app_id\n    and scope = ''\n    and name = any(array[\n      'Apdex',\n      'HttpDispatcher'\n    ])\n  order by point desc\n)\nselect\n  point as time,\n  'Requests count' as metric,\n  \"call-count\" as value\nfrom data\nwhere name = 'HttpDispatcher'\nunion all\nselect\n  point as time,\n  'Response time' as metric,\n  \"total-call-time\" / \"call-count\" as value\nfrom data\nwhere name = 'HttpDispatcher'\nunion all\nselect\n  point as time,\n  'Apdex' as metric,\n  (s + t/2) / (s + t + f) as value\nfrom (\n  select\n    point,\n    \"call-count\" as s,\n    \"total-call-time\" as t,\n    \"total-exclusive-time\" as f\n  from data\n  where name = 'Apdex'\n) as x\nunion all\nselect\n  point as time,\n  'Satisfied' as metric,\n  s / (s + t + f) as value\nfrom (\n  select\n    point,\n    \"call-count\" as s,\n    \"total-call-time\" as t,\n    \"total-exclusive-time\" as f\n  from data\n  where name = 'Apdex'\n) as x\nunion all\nselect\n  point as time,\n  'Tolerating' as metric,\n  t / (s + t + f) as value\nfrom (\n  select\n    point,\n    \"call-count\" as s,\n    \"total-call-time\" as t,\n    \"total-exclusive-time\" as f\n  from data\n  where name = 'Apdex'\n) as x\nunion all\nselect\n  point as time,\n  'Frustrated' as metric,\n  f / (s + t + f) as value\nfrom (\n  select\n    point,\n    \"call-count\" as s,\n    \"total-call-time\" as t,\n    \"total-exclusive-time\" as f\n  from data\n  where name = 'Apdex'\n) as x"
    }
   ]
  },
  {
   "title": "Weekly",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "with data as (\n  select\n    point,\n    sum(\"call-count\")           as \"call-count\",\n    sum(\"total-call-time\")      as \"total-call-time\",\n    sum(\"total-exclusive-time\") as \"total-exclusive-time\",\n    min(\"min-call-time\")        as \"min-call-time\",\n    max(\"max-call-time\")        as \"max-call-time\",\n    sum(\"sum-of-squares\")       as \"sum-of-squares\",\n    scope, name\n  from (\n    select\n      date_trunc('week', point) as point,\n      \"call-count\",\n      \"total-call-time\",\n      \"total-exclusive-time\",\n      \"min-call-time\",\n      \"max-call-time\",\n      \"sum-of-squares\",\n      scope, name\n    from \"metric-data-by-day-ext\"\n    where\n      point >= date_trunc('day', now()) - interval '3 month'\n      and \"app-id\" = $app_id\n      and scope = ''\n      and name = any(array[\n        'Apdex',\n        'HttpDispatcher'\n      ])\n  ) as x\n  group by point, scope, name\n  order by point desc\n)\nselect\n  point as time,\n  'Requests count' as metric,\n  \"call-count\" as value\nfrom data\nwhere name = 'HttpDispatcher'\nunion all\nselect\n  point as time,\n  'Response time' as metric,\n  \"total-call-time\" / \"call-count\" as value\nfrom data\nwhere name = 'HttpDispatcher'\nunion all\nselect\n  point as time,\n  'Apdex' as metric,\n  (s + t/2) / (s + t + f) as value\nfrom (\n  select\n    point,\n    \"call-count\" as s,\n    \"total-call-time\" as t,\n    \"total-exclusive-time\" as f\n  from data\n  where name = 'Apdex'\n) as x\nunion all\nselect\n  point as time,\n  'Satisfied' as metric,\n  s / (s + t + f) as value\nfrom (\n  select\n    point,\n    \"call-count\" as s,\n    \"total-call-time\" as t,\n    \"total-exclusive-time\" as f\n  from data\n  where name = 'Apdex'\n) as x\nunion all\nselect\n  point as time,\n  'Tolerating' as metric,\n  t / (s + t + f) as value\nfrom (\n  select\n    point,\n    \"call-count\" as s,\n    \"total-call-time\" as t,\n    \"total-exclusive-time\" as f\n  from data\n  where name = 'Apdex'\n) as x\nunion all\nselect\n  point as time,\n  'Frustrated' as metric,\n  f / (s + t + f) as value\nfrom (\n  select\n    point,\n    \"call-count\" as s,\n    \"total-call-time\" as t,\n    \"total-exclusive-time\" as f\n  from data\n  where name = 'Apdex'\n) as x"
    }
   ]
  },
  {
   "title": "Monthly",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "with data as (\n  select\n    point,\n    sum(\"call-count\")           as \"call-count\",\n    sum(\"total-call-time\")      as \"total-call-time\",\n    sum(\"total-exclusive-time\") as \"total-exclusive-time\",\n    min(\"min-call-time\")        as \"min-call-time\",\n    max(\"max-call-time\")        as \"max-call-time\",\n    sum(\"sum-of-squares\")       as \"sum-of-squares\",\n    scope, name\n  from (\n    select\n      date_trunc('month', point) as point,\n      \"call-count\",\n      \"total-call-time\",\n      \"total-exclusive-time\",\n      \"min-call-time\",\n      \"max-call-time\",\n      \"sum-of-squares\",\n      scope, name\n    from \"metric-data-by-day-ext\"\n    where\n      point >= date_trunc('day', now()) - interval '1 year'\n      and \"app-id\" = $app_id\n      and scope = ''\n      and name = any(array[\n        'Apdex',\n        'HttpDispatcher'\n      ])\n  ) as x\n  group by point, scope, name\n  order by point desc\n)\nselect\n  point as time,\n  'Requests count' as metric,\n  \"call-count\" as value\nfrom data\nwhere name = 'HttpDispatcher'\nunion all\nselect\n  point as time,\n  'Response time' as metric,\n  \"total-call-time\" / \"call-count\" as value\nfrom data\nwhere name = 'HttpDispatcher'\nunion all\nselect\n  point as time,\n  'Apdex' as metric,\n  (s + t/2) / (s + t + f) as value\nfrom (\n  select\n    point,\n    \"call-count\" as s,\n    \"total-call-time\" as t,\n    \"total-exclusive-time\" as f\n  from data\n  where name = 'Apdex'\n) as x\nunion all\nselect\n  point as time,\n  'Satisfied' as metric,\n  s / (s + t + f) as value\nfrom (\n  select\n    point,\n    \"call-count\" as s,\n    \"total-call-time\" as t,\n    \"total-exclusive-time\" as f\n  from data\n  where name = 'Apdex'\n) as x\nunion all\nselect\n  point as time,\n  'Tolerating' as metric,\n  t / (s + t + f) as value\nfrom (\n  select\n    point,\n    \"call-count\" as s,\n    \"total-call-time\" as t,\n    \"total-exclusive-time\" as f\n  from data\n  where name = 'Apdex'\n) as x\nunion all\nselect\n  point as time,\n  'Frustrated' as metric,\n  f / (s + t + f) as value\nfrom (\n  select\n    point,\n    \"call-count\" as s,\n    \"total-call-time\" as t,\n    \"total-exclusive-time\" as f\n  from data\n  where name = 'Apdex'\n) as x"
    }
   ]
  }
 ]
}