{
 "title": "Transaction trace",
 "time": { "from": "2020-01-30T14:02:30.381Z", "to": "2020-01-30T14:32:30.381Z" },
 "templating": {
  "list": [
   { "name": "trace_id", "query": "not_selected" },
   { "name": "app_id", "query": "not_selected" },
   { "name": "scope", "label": "scope", "query": "not_selected" }
  ]
 },
 "panels": [
  {
   "title": "App name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select name\nfrom apps\nwhere id = $app_id\n"
    }
   ]
  },
  {
   "title": "Scope",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "rawSql": "select '$scope'" }
   ]
  },
  {
   "title": "Attrs",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "select \"start-time\", duration, uri, host\nfrom \"transaction-sample-data-ext\" as data\njoin servers on servers.id = data.\"server-id\"\nwhere\n  $__timeFilter(\"start-time\")\n  and data.\"app-id\" = $app_id\n  and data.\"transaction-name\" = any(array['$scope',\n                                          'WebTransaction/$scope',\n                                          'OtherTransaction/$scope'])\n  and data.id = $trace_id"
    }
   ]
  },
  {
   "title": "Description",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "select html\nfrom \"transaction-sample-data-ext\" as data\nwhere\n  -- чтобы индекс использовался, нет индекса по id\n  $__timeFilter(\"start-time\")\n  and data.\"app-id\" = $app_id\n  and data.\"transaction-name\" = any(array['$scope',\n                                          'WebTransaction/$scope',\n                                          'OtherTransaction/$scope'])\n  and data.id = $trace_id"
    }
   ]
  }
 ]
}