{
 "title": "Web",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "app_id", "query": "not_selected" }
  ]
 },
 "panels": [
  {
   "title": "App name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select name\nfrom apps\nwhere id = $app_id\n"
    }
   ]
  },
  {
   "title": "Web response",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  name as metric,\n\n  sum(val)\n  /\n  sum(sum(\"call-count\")) filter (where name = 'HttpDispatcher')\n                         over (partition by time)\n  as val\nfrom (\n  select\n    $__timeGroup(point, $interval, 0),\n    name,\n    \"call-count\",\n    case when \"total-exclusive-time\" = 0\n    then \"total-call-time\"\n    else \"total-exclusive-time\"\n    end as val\n  from \"metric-data-ext\"\n  where\n    $__timeFilter(point)\n    and \"app-id\" = $app_id\n    and scope = ''\n    and name like any(array[\n      'HttpDispatcher',\n      'WebTransactionTotalTime',\n      'Middleware/all',\n      'External/allWeb',\n      'Datastore/%/allWeb'\n    ])\n) as x\ngroup by time, name\norder by time"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  sum(\"call-count\") / extract(epoch from interval '$interval') * 60 as val,\n  'current' as metric\nfrom \"metric-data-ext\"\nwhere\n  point between\n    $__timeFrom()::timestamptz\n    and\n    $__timeTo()::timestamptz\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'HttpDispatcher'\ngroup by time\nunion all\nselect\n  $__timeGroup(point + interval '1 day', $interval, 0),\n  sum(\"call-count\") / extract(epoch from interval '$interval') * 60 as val,\n  '-1 day' as metric\nfrom \"metric-data-ext\"\nwhere\n  point between\n    $__timeFrom()::timestamptz - interval '1 day'\n    and\n    $__timeTo()::timestamptz - interval '1 day'\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'HttpDispatcher'\ngroup by time\nunion all\nselect\n  $__timeGroup(point + interval '1 week', $interval, 0),\n  sum(\"call-count\") / extract(epoch from interval '$interval') * 60 as val,\n  '-1 week' as metric\nfrom \"metric-data-ext\"\nwhere\n  point between\n    $__timeFrom()::timestamptz - interval '1 week'\n    and\n    $__timeTo()::timestamptz - interval '1 week'\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'HttpDispatcher'\ngroup by time\n\norder by time"
    }
   ]
  },
  {
   "title": "Apdex",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  (s + t/2) / (s + t + f) as val,\n  'current' as metric\nfrom (\n  select\n    $__timeGroup(point, $interval, 0),\n    sum(\"call-count\") as s,\n    sum(\"total-call-time\") as t,\n    sum(\"total-exclusive-time\") as f\n  from \"metric-data-ext\"\n  where\n    point between\n      $__timeFrom()::timestamptz\n      and\n      $__timeTo()::timestamptz\n    and \"app-id\" = $app_id\n    and scope = ''\n    and name = 'Apdex'\n  group by time\n) as res\nunion all\nselect\n  time,\n  (s + t/2) / (s + t + f) as val,\n  '-1 day' as metric\nfrom (\n  select\n    $__timeGroup(point + interval '1 day', $interval, 0),\n    sum(\"call-count\") as s,\n    sum(\"total-call-time\") as t,\n    sum(\"total-exclusive-time\") as f\n  from \"metric-data-ext\"\n  where\n    point between\n      $__timeFrom()::timestamptz - interval '1 day'\n      and\n      $__timeTo()::timestamptz - interval '1 day'\n    and \"app-id\" = $app_id\n    and scope = ''\n    and name = 'Apdex'\n  group by time\n) as res\nunion all\nselect\n  time,\n  (s + t/2) / (s + t + f) as val,\n  '-1 week' as metric\nfrom (\n  select\n    $__timeGroup(point + interval '1 week', $interval, 0),\n    sum(\"call-count\") as s,\n    sum(\"total-call-time\") as t,\n    sum(\"total-exclusive-time\") as f\n  from \"metric-data-ext\"\n  where\n    point between\n      $__timeFrom()::timestamptz - interval '1 week'\n      and\n      $__timeTo()::timestamptz - interval '1 week'\n    and \"app-id\" = $app_id\n    and scope = ''\n    and name = 'Apdex'\n  group by time\n) as res\n\norder by time"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "select *\nfrom (\n  select\n    time,\n    name as metric,\n    sum(\"call-count\")\n    / sum(sum(\"call-count\")) filter (where name = 'HttpDispatcher')\n                             over (partition by time)\n    -- здесь не нужно делать поправку на $interval, т.к. это безразмерные проценты\n    as val\n  from (\n    select\n      $__timeGroup(point, $interval, 0),\n      name,\n      \"call-count\"\n    from \"metric-data-ext\"\n    where\n      $__timeFilter(point)\n      and \"app-id\" = $app_id\n      and scope = ''\n      and name in ('HttpDispatcher', 'Errors/allWeb')\n  ) as x\n  group by time, name\n) as res\nwhere metric != 'HttpDispatcher'\norder by time\n"
    }
   ]
  },
  {
   "title": "Histogram",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "with\nstat as (\n  select\n    percentile_cont(0.99) within group (order by duration asc)  as max,\n    count(*) as total\n  from \"analytic-event-data-ext\"\n  where\n    $__timeFilter(timestamp)\n    and \"app-id\" = $app_id\n    and \"transaction-name\" like any(array['Controller/%', 'WebTransaction/%'])\n),\nbucket_nums as (\n  select * from generate_series(1, 101) as buckets(i)\n),\nbuckets as (\n  select\n    width_bucket(duration, 0, max, 100) as bucket,\n    count(*) as count\n  from \"analytic-event-data-ext\", stat\n  where\n    $__timeFilter(timestamp)\n    and \"app-id\" = $app_id\n    and \"transaction-name\" like any(array['Controller/%', 'WebTransaction/%'])\n  group by bucket\n)\n\n  select\n    (i - 1) * max / 100 as start,\n    coalesce(count::float, .0) / total::float * 100 as percent,\n    coalesce(count, 0) as count\n  from stat, bucket_nums\n  left join buckets on i = bucket\n"
    }
   ]
  },
  {
   "title": "Percentiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(timestamp, $interval, 0),\n  percentile_cont(0.99) within group (order by duration asc) as \"0.99\",\n  percentile_cont(0.95) within group (order by duration asc) as \"0.95\",\n  percentile_cont(0.50) within group (order by duration asc) as median,\n  avg(duration) as avg\nfrom \"analytic-event-data-ext\"\nwhere\n  $__timeFilter(timestamp)\n  and \"app-id\" = $app_id\n  and \"transaction-name\" like any(array['Controller/%', 'WebTransaction/%'])\ngroup by time\n"
    }
   ]
  },
  {
   "title": "Historical response",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  sum(\"total-call-time\") / sum(\"call-count\") as val,\n  'current' as metric\nfrom \"metric-data-ext\"\nwhere\n  point between\n    $__timeFrom()::timestamptz\n    and\n    $__timeTo()::timestamptz\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'HttpDispatcher'\ngroup by time\nunion all\nselect\n  $__timeGroup(point + interval '1 day', $interval, 0),\n  sum(\"total-call-time\") / sum(\"call-count\") as val,\n  '-1 day' as metric\nfrom \"metric-data-ext\"\nwhere\n  point between\n    $__timeFrom()::timestamptz - interval '1 day'\n    and\n    $__timeTo()::timestamptz - interval '1 day'\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'HttpDispatcher'\ngroup by time\nunion all\nselect\n  $__timeGroup(point + interval '1 week', $interval, 0),\n  sum(\"total-call-time\") / sum(\"call-count\") as val,\n  '-1 week' as metric\nfrom \"metric-data-ext\"\nwhere\n  point between\n    $__timeFrom()::timestamptz - interval '1 week'\n    and\n    $__timeTo()::timestamptz - interval '1 week'\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'HttpDispatcher'\ngroup by time\n\norder by time"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "select\n  replace(name, 'WebTransactionTotalTime/', '')  as metric,\n  sum(\"total-call-time\") / sum(sum(\"total-call-time\")) over () as percent,\n  sum(\"total-call-time\") / sum(\"call-count\") as avg,\n  sum(\"call-count\")\n    / extract(epoch from $__timeTo()::timestamp - $__timeFrom()::timestamp)\n    * 60 as rpm,\n  min(\"min-call-time\") as min,\n  max(\"max-call-time\") as max\nfrom \"metric-data-ext\"\nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name like 'WebTransactionTotalTime/%'\ngroup by name\n"
    }
   ]
  },
  {
   "title": "By server",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "with\ndata as (\n  select\n    \"server-id\",\n    name,\n    sum(\"call-count\") as \"call-count\",\n    sum(\"total-call-time\") as \"total-call-time\",\n    sum(\"total-exclusive-time\") as \"total-exclusive-time\"\n  from \"metric-data-ext\"\n  where\n    $__timeFilter(point)\n    and \"app-id\" = $app_id\n    and scope = ''\n    and name = any(array[\n      'Apdex',\n      'HttpDispatcher',\n      'Errors/allWeb',\n      'CPU/User Time',\n      'Memory/Physical'\n    ])\n  group by \"server-id\", name\n),\napdex as (\n  select\n    \"server-id\",\n    (s + t/2) / (s + t + f) as val\n  from (\n    select\n      \"server-id\",\n      \"call-count\" as s,\n      \"total-call-time\" as t,\n      \"total-exclusive-time\" as f\n    from data\n    where name = 'Apdex'\n  ) as res\n),\nhttp_tx as (\n  select\n    \"server-id\",\n    \"total-call-time\" as time,\n    \"call-count\" as calls\n  from data\n  where name = 'HttpDispatcher'\n),\nerrors as (\n  select\n    \"server-id\",\n    \"call-count\" as count\n  from data\n  where name = 'Errors/allWeb'\n),\n/* проверить бы что оно показывает то, что нужно */\ncpu as (\n  select\n    \"server-id\",\n     -- total-call-time - это кол-во секунд, потраченной в юзерспейсе,\n     -- т.к. у нас данные за минуту, то чтобы получить проценты нужно делить на 60\n    \"total-call-time\" / 60 / extract(epoch from $__timeTo()::timestamp - $__timeFrom()::timestamp) * 60 as val\n  from data\n  where name = 'CPU/User Time'\n),\nmemory as (\n  select\n    \"server-id\",\n    \"total-call-time\" / extract(epoch from $__timeTo()::timestamp - $__timeFrom()::timestamp) * 60 as val\n  from data\n  where name = 'Memory/Physical'\n)\nselect\n  servers.host,\n  apdex.val as apdex,\n  http_tx.time / http_tx.calls as resp,\n  http_tx.calls / extract(epoch from $__timeTo()::timestamp - $__timeFrom()::timestamp) * 60 as rpm,\n  errors.count / http_tx.calls as errors,\n  cpu.val as cpu,\n  memory.val as memory\nfrom servers\nleft join apdex on servers.id = apdex.\"server-id\"\njoin http_tx on servers.id = http_tx.\"server-id\"\nleft join errors on servers.id = errors.\"server-id\"\nleft join cpu on servers.id = cpu.\"server-id\"\nleft join memory on servers.id = memory.\"server-id\"\nwhere\n  servers.\"app-id\" = $app_id"
    }
   ]
  },
  {
   "title": "Response by server",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  sum(\"total-call-time\") / sum(\"call-count\") as val,\n  host as metric\nfrom \"metric-data-ext\" as data\njoin servers on servers.id = data.\"server-id\"\nwhere\n  $__timeFilter(point)\n  and data.\"app-id\" = $app_id\n  and scope = ''\n  and name = 'HttpDispatcher'\ngroup by time, host\norder by time "
    }
   ]
  },
  {
   "title": "Throughput by server",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  sum(\"call-count\") / extract(epoch from interval '$interval') * 60 as val,\n  host as metric\nfrom \"metric-data-ext\" as data\njoin servers on servers.id = data.\"server-id\"\nwhere\n  $__timeFilter(point)\n  and data.\"app-id\" = $app_id\n  and scope = ''\n  and name = 'HttpDispatcher'\ngroup by time, host\norder by time"
    }
   ]
  },
  {
   "title": "Scalability",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(point, $interval, 0),\n  sum(\"call-count\") / extract(epoch from interval '$interval') * 60 as rpm,\n  sum(\"total-call-time\") / sum(\"call-count\") as resp,\n  extract(hour from min(point) at time zone 'MSK') as hour\nfrom \"metric-data-ext\" \nwhere\n  $__timeFilter(point)\n  and \"app-id\" = $app_id\n  and scope = ''\n  and name = 'HttpDispatcher'\ngroup by time\n"
    }
   ]
  },
  {
   "title": "Top 5 web transactions ",
   "type": "graph",
   "description": "by percent of wall clock time",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  replace(name, 'WebTransactionTotalTime/Controller/', '')  as metric,\n  val\nfrom (\n  select\n    time,\n    name,\n    val,\n    dense_rank() over (order by total desc) as rank\n  from (\n    select\n      $__timeGroup(point, $interval, 0),\n      name,\n      sum(\"total-call-time\")\n        / extract(epoch from interval '$interval')\n      as val,\n      sum(sum(\"total-call-time\")) over (partition by name) as total\n    from \"metric-data-ext\"\n    where\n      $__timeFilter(point)\n      and \"app-id\" = $app_id\n      and scope = ''\n      and name like 'WebTransactionTotalTime/Controller/%'\n    group by time, name\n  ) as x\n) as res\nwhere rank <= 5\norder by time\n"
    }
   ]
  }
 ]
}