name: Statsbit

on:
  push:
    branches: [ master, development ]
    paths:
    - '.github/**'
    - 'backend/**'
    - 'grafana/**'

defaults:
  run:
    working-directory: backend

jobs:
  backend-test:
    runs-on: ubuntu-latest
    container: clojure:openjdk-11-tools-deps-1.10.1.739
    services:
      postgres:
        image: timescale/timescaledb:1.7.4-pg11
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      STATSBIT_BACKEND_DB_NAME: postgres
      STATSBIT_BACKEND_DB_HOST: postgres
      STATSBIT_BACKEND_DB_PORT: 5432
      STATSBIT_BACKEND_DB_USER: postgres
      STATSBIT_BACKEND_DB_PASSWORD: password
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: /root/.m2
        key: test-${{ hashFiles('backend/deps.edn') }}
        restore-keys: test-
    - run: clojure -M:dev -m ru.bia-tech.statsbit.migration test
    - run: clojure -M:dev:run-tests


  backend-build:
    needs: backend-test
    runs-on: ubuntu-latest
    container: clojure:openjdk-11-tools-deps-1.10.1.739
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: /root/.m2
        key: build-${{ hashFiles('backend/deps.edn') }}
        restore-keys: build-
    - run: clojure -X:prod:depstar
    - uses: actions/upload-artifact@v2
      with:
        name: app.jar
        path: backend/build/app.jar


  backend-docker:
    needs: backend-build
    runs-on: ubuntu-latest
    steps:
      - uses: rlespinasse/github-slug-action@v3.x
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: app.jar
          path: backend/build

      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./backend/build
          file: ./backend/build/Dockerfile
          push: true
          tags: biatechru/statsbit:${{ env.GITHUB_REF_SLUG }}-backend-${{ github.run_number }}-${{ env.GITHUB_SHA_SHORT }}


  grafana-docker:
    needs: backend-build
    runs-on: ubuntu-latest
    steps:
      - uses: rlespinasse/github-slug-action@v3.x
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./grafana
          file: ./grafana/Dockerfile
          push: true
          tags: biatechru/statsbit:${{ env.GITHUB_REF_SLUG }}-grafana-${{ github.run_number }}-${{ env.GITHUB_SHA_SHORT }}
